name: Shopping list app CI



on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  

  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 15.0
        uses: actions/setup-node@v1
        with:
          node-version: 15.0
      
      - name: Install dependencies
        run: npm ci      
        
      - name: Chache Node Modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      
  



  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci              
      - name: Lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci              
      - name: Build
        run: npm run build -- --prod

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci              
      - name: Test
        run: npm test -- --configuration=ci
  
  # release:
  
  # deploy:
  





  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js 15.0
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: 15.0
    
  #   - name: Install dependencies
  #     run: npm ci
    
    
  #   - run: npm run build --if-present
  #   - name: Release
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  #     run: npx semantic-release