name: Shopping list app CI



on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  

  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 15.0
        uses: actions/setup-node@v1
        with:
          node-version: 15.0
      
      - name: Install dependencies
        run: npm ci      
        
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-  
      
  



  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 15.0
        uses: actions/setup-node@v1
        with:
          node-version: 15.0
      - name: Lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 15.0
        uses: actions/setup-node@v1
        with:
          node-version: 15.0
      - name: Build
        run: npm run build -- --prod

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 15.0
        uses: actions/setup-node@v1
        with:
          node-version: 15.0
      - name: Test
        run: npm test -- --no-watch
  
  # release:
  
  # deploy:
  





  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js 15.0
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: 15.0
    
  #   - name: Install dependencies
  #     run: npm ci
    
    
  #   - run: npm run build --if-present
  #   - name: Release
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  #     run: npx semantic-release