name: Shopping list app CI



on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  

  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 15.0
        uses: actions/setup-node@v1
        with:
          node-version: 15.0
      
      - name: Install dependencies
        run: npm ci      
        
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: node_modules
          path: node_modules
          retention-minutes: 30        
      
  



  verify:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 15.0
        uses: actions/setup-node@v1
        with:
          node-version: 15.0
      - name: Download node modules
        uses: actions/download-artifact@v2
        with:
          name: node_modules
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build -- --prod
      - name: Test
        run: npm test -- --no-watch
  
  # release:
  
  # deploy:
  





  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js 15.0
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: 15.0
    
  #   - name: Install dependencies
  #     run: npm ci
    
    
  #   - run: npm run build --if-present
  #   - name: Release
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  #     run: npx semantic-release